config/routes.rb
Rails.application.routes.draw do

 root 'static_pages#home'
 get '/help', to: 'static_pages#help'
 get '/about', to: 'static_pages#about'
 get '/contact', to: 'static_pages#contact'
 get '/signup', to: 'users#new'
 post '/signup',  to: 'users#create'
 get '/team', to: 'static_pages#team'
 resources :users
 
 get '/computing', to: 'static_pages#computing'
 get '/finance', to: 'static_pages#finance'
 get '/philosophy', to: 'static_pages#philosophy'
 get '/lifestyle', to: 'static_pages#lifestyle'
 get '/politics', to: 'static_pages#politics'
end

  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
  def team
  end
  
  def computing
  end
  def politics
  end
  def finance
  end
  def lifestyle
  end
  def philosophy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Korda!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  #Returns the full title on a per-page basis.
  def full_title(page_title = ' ')
    base_title = "Korda.io"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}" 
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This website is still in development
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://www.youtube.com/watch?v=e-7UbU45a1U">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "KORDA.IO", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-middle">
            <li><%= link_to "Computing",   computing_path %></li>
            <li><%= link_to "Finance",   finance_path %></li>
            <li><%= link_to "Philosophy",   philosophy_path %></li>
            <li><%= link_to "Lifestyle",   lifestyle_path %></li>
            <li><%= link_to "Politics",   politics_path %></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
            <li><%= link_to "Log in", '#' %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <%= render 'layouts/shim' %>
  </head>
  <body>
   <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
       <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<%provide(:title, "About") %>
  <h1> Korda.io</h1>
    <p> 
      Welcome to the about page
    </p>

app/views/static_pages/computing.html.erb
<%provide(:title, "Computing") %>
  <h1> Korda.io</h1>
    <p> 
      Welcome to the Computing page
    </p>

app/views/static_pages/contact.html.erb
<%provide(:title, "Contact") %>
  <h1> Korda.io</h1>
    <p> 
      Welcome to the contact page
    </p>

app/views/static_pages/finance.html.erb
<%provide(:title, "Finance") %>
  <h1> Korda.io</h1>
    <p> 
      Welcome to the finance page!
    </p>

app/views/static_pages/help.html.erb
<%provide(:title, "Help") %>
  <h1> Korda.io</h1>
    <p> 
      Welcome to the help page
    </p>
    
    

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Korda</h1>

  <h2>
    An <%=link_to "Elite Team", team_path %> on the Internet
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-danger" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/static_pages/lifestyle.html.erb
<%provide(:title, "Lifestyle") %>
  <h1> Korda.io</h1>
    <p> 
      Welcome to the lifestyle page
    </p>

app/views/static_pages/philosophy.html.erb
<%provide(:title, "Philosophy") %>
  <h1> Korda.io</h1>
    <p> 
      Welcome to the philosophy page
    </p>

app/views/static_pages/politics.html.erb
<%provide(:title, "Politics") %>
  <h1> Korda.io</h1>
    <p> 
      Welcome to the politics page
    </p>

app/views/static_pages/team.html.erb
<%provide(:title, "Team") %>
  <h1> Korda.io</h1>
    <p> 
      Meet the team!
    </p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>